# @name criarTurma
POST http://localhost:3003/class/
Content-Type: application/json

{
    "nome": "Franklin"
}

###

# @name pegarTurmasAtivas
GET http://localhost:3003/class/active
Content-Type: application/json

###

# @name alteraModuloDaTurma
PUT http://localhost:3003/class/8ff94799-34e3-4adc-a920-d5fd0569a46f/module
Content-Type: application/json

{
    "modulo": 3
}


###

# @name criarEstudante
POST http://localhost:3003/student/
Content-Type: application/json

{
    "nome": "Luan Santana",
    "email": "meteoro@dapaixao.com.br",
    "data_nasc": "1995-04-26",
    "turma_id": "8ff94799-34e3-4adc-a920-d5fd0569a4f"
}

###

# @name pegarEstudantePeloNome
GET http://localhost:3003/student/name
Content-Type: application/json

{
    "nome": "Luan"
}

###

# @name trocarTurmaDoEstudante
PUT http://localhost:3003/student/adac67cb-a8d5-4ebf-9c71-cc9d95666366/class
Content-Type: application/json

{
    "turma_id": "0001"
}

###

# @name criarDocente

POST http://localhost:3003/teacher/
Content-Type: application/json

{
    "nome": "Edmar",
    "email": "edmar@labenu.brabo.br",
    "data_nasc": "1996-02-03",
    "turma_id": "0001"
}

###

# @name pegarTodosDocentes

GET http://localhost:3003/teachers/
Content-Type: application/json

###

# @name trocarTurmaDoDocente

PUT http://localhost:3003/teacher/1da0e17a-2a5a-4d7e-be64-e44f5605b2e7/class
Content-Type: application/json

{
    "turma_id": "8ff94799-34e3-4adc-a920-d5fd0569a46f"
}
